-- Fix roles: ADMIN,COORDINATOR,SUPERVISOR,STUDENT (was ADMIN,SUPERVISOR,COMPANY,STUDENT) + add Requirement PDF template
UPDATE `User` SET `role`='COORDINATOR' WHERE `role`='COMPANY';
ALTER TABLE `User` MODIFY `role` ENUM('ADMIN','COORDINATOR','SUPERVISOR','STUDENT') NOT NULL DEFAULT 'STUDENT';
-- Allow PDF template as base64 LONGTEXT + filename
ALTER TABLE `Requirement` MODIFY `templateFile` LONGTEXT NULL;
ALTER TABLE `Requirement` ADD COLUMN `templateFileName` VARCHAR(191) NULL AFTER `templateFile`;
